apiVersion: apps/v1
kind: Deployment
metadata:
  name: drift-detector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: drift-detector
  template:
    metadata:
      labels:
        app: drift-detector
    spec:
      containers:
        - name: drift-detector
          image: drift-detector:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /monitor/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /monitor/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: drift-detector-service
spec:
  selector:
    app: drift-detector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drift-detector-ingress
spec:
  rules:
    - http:
        paths:
          - path: /monitor
            pathType: Prefix
            backend:
              service:
                name: drift-detector-service
                port:
                  number: 80
